export const travel = [
	{
		id: 1,
		city: 'Mountain',
		country: 'Nepal',
		reviews: '4,5',
		weather: '21°',
		hotels: '1000$+',
		people: '100,000+',
		img: 'mountain.jpg',
	},
	{
		id: 2,
		city: 'Lake',
		country: 'India',
		reviews: '4,7',
		weather: '25°',
		hotels: '1300$+',
		people: '210,000+',
		img: 'lake.jpg',
	},
	{
		id: 3,
		city: 'Mountain',
		country: 'Nepal',
		reviews: '4,5',
		weather: '21°',
		hotels: '1000$+',
		people: '100,000+',
		img: 'mountain.jpg',
	},
	{
		id: 4,
		city: 'Lake',
		country: 'India',
		reviews: '4,7',
		weather: '25°',
		hotels: '1300$+',
		people: '210,000+',
		img: 'lake.jpg',
	},
	{
		id: 5,
		city: 'Mountain',
		country: 'Nepal',
		reviews: '4,5',
		weather: '21°',
		hotels: '1000$+',
		people: '100,000+',
		img: 'mountain.jpg',
	},
	{
		id: 6,
		city: 'Lake',
		country: 'India',
		reviews: '4,7',
		weather: '25°',
		hotels: '1300$+',
		people: '210,000+',
		img: 'lake.jpg',
	},
]

export const info = [
	{
		firstText: 'Book and',
		secondText: 'mind your own business',
		img: 'info-1.png',
		infoText: 'Tickets',
		infoDescription: 'Make a booking with us and enjoy',
	},
	{
		firstText: 'We find',
		secondText: 'the best hotels',
		img: 'info-2.png',
		infoText: 'Hotels',
		infoDescription: 'The Ideal Hotel at a Great Price',
	},
	{
		firstText: 'Tours',
		secondText: 'Adventures Activities',
		img: 'info-3.png',
		infoText: 'Adventure',
		infoDescription: 'Find & book tours, adventures, activities',
	},
]
